
- logs: #optional
    info: ./logs/debug.log
    error: ./logs/exceptions.log

- dbsets: "./dbsets"

- mappings:
    default: "./mappings/default.yaml"
    requests: ["./mappings/response.yaml", "./mappings/strategy.yaml", "./mappings/post.yaml"]

- server:
    port: 9999

- stubs: #optional
    #path: "/home/user/spikes/nodestub/resonses/"
    path: "./responses/"